version: '2'
services:
  eurekaserver:
     image:   citadel/tmx-eureka-service:v7a
     ports:
       - "8761:8761"
  configserver:
    image: citadel/tmx-confsvr:v7a
    ports:
       - "8762:8762"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMETRIC"       
  zipkin:
    image: citadel/tmx-zipkinsvr:v7a
    ports:
      - "9411:9411"
    environment:
      SERVER_PORT: "9411"
  logspout:
    image: gliderlabs/logspout
    command: syslog://logs5.papertrailapp.com:33437
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock        