zuul.ignored-services: "*"
zuul.prefix:  /api
zuul.routes.pupilservice: /pupil/**
zuul.routes.addressservice: /address/**
zuul.sensitiveHeaders: Cookie,Set-Cookie
zuul.debug.request: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.command.pupilservice.execution.isolation.thread.timeoutInMilliseconds: 7500
hystrix.command.addressservice.execution.isolation.thread.timeoutInMilliseconds: 5000
pupilservice.ribbon.ReadTimeout: 7550
addressservice.ribbon.ReadTimeout: 5000
