server:
   port: 8085
spring:
  application:
    name: addressservice
  profiles:
    active:
      default
  zipkin:
    baseUrl: http://localhost:9411      
  cloud:
    config:
      enabled: false
      
security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8763/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/